#:kivy 2.2.0
#:import dp kivy.metrics.dp
#:import BeanRoastAnim widgets.bean_roast_anim.BeanRoastAnim
#:import Clock kivy.clock.Clock
#:import ButtonBehavior kivy.uix.behaviors.ButtonBehavior
#:import StatusLed widgets.status_led.StatusLed

<HoldArea@ButtonBehavior+Widget>:

<HomeScreen>:

    BoxLayout:
        orientation: "vertical"
        padding: dp(40)
        spacing: dp(26)

        canvas.before:
            Color:
                rgba: 0.07, 0.08, 0.10, 1
            Rectangle:
                pos: self.pos
                size: self.size

        Widget:
            size_hint_y: 1


        BoxLayout:
            size_hint_y: None
            height: dp(180)

            AnchorLayout:
                anchor_x: "center"
                anchor_y: "center"

                BoxLayout:
                    orientation: "horizontal"
                    size_hint: None, None
                    size: self.minimum_size
                    spacing: dp(14)

                    ClickLabel:
                        text: "Sigma Coffee Roaster\nProfesional"
                        font_size: "54sp"
                        bold: True
                        color: 0.92, 0.94, 0.98, 1
                        halign: "center"
                        valign: "middle"
                        text_size: None, None
                        size_hint: None, None
                        size: self.texture_size
                        on_release: root.go_live()

                    StatusLed:
                        size_hint: None, None
                        size: dp(10), dp(10)
                        pos_hint: {"center_y": 0.35}
                        state: "on" if app.modbus_connected else "off"
                        blink: True

        #BoxLayout:
        #    size_hint_y: None
        #    height: dp(180)

        #    ClickLabel:
        #        text: "Sigma Coffee Roaster\nProfesional"
        #        font_size: "54sp"
        #        bold: True
        #        color: 0.92, 0.94, 0.98, 1
        #        halign: "center"
        #        valign: "middle"
        #        text_size: self.size
        #        on_release: root.go_live()

        FloatLayout:
            size_hint_y: None
            height: dp(260)

            BeanRoastAnim:
                id: roast_anim_home
                size_hint: None, None
                size: dp(340), dp(220)
                center_x: self.parent.center_x
                center_y: self.parent.center_y
                green_source: "assets/beans/bean_green_transparent.png"
                dark_source: "assets/beans/bean_dark_transparent.png"
                intensity: 0.8

        FloatLayout:
            size_hint_y: 1

            HoldArea:
                size_hint: None, None
                size: dp(140), dp(140)
                pos_hint: {"right": 1, "y": 0}
                opacity: 0

                on_press: root.start_close_hold()
                on_release: root.cancel_close_hold()
