#:kivy 2.2.0
#:import dp kivy.metrics.dp
#:import AirflowGauge widgets.airflow_gauge.AirflowGauge
#:import RoastPlot widgets.roast_plot.RoastPlot
#:import ButtonBehavior kivy.uix.behaviors.ButtonBehavior

# -----------------------------
# Plot hold area (invisible)
# -----------------------------
<PlotHoldArea@ButtonBehavior+Widget>:
    # görünmez, sadece dokunmayı yakalar


# =========================================================
# LIVE ROAST SCREEN
# =========================================================

<LiveRoastScreen>:
    BoxLayout:
        orientation: "vertical"
        padding: dp(12)
        spacing: dp(10)

        canvas.before:
            Color:
                rgba: 0.07, 0.08, 0.10, 1
            Rectangle:
                pos: self.pos
                size: self.size

        # ---------------- TOP TABS ----------------
        BoxLayout:
            size_hint_y: None
            height: dp(64)
            spacing: dp(14)

            DarkTab:
                text: "Manuel Control"
                tab_key: "manual"
                font_size: "25sp"
                bold: True
                color: 1, 1, 1, 1
                on_release: root.manager.current = "manual"

            DarkTab:
                text: "Make Profile"
                tab_key: "make_profile"
                font_size: "25sp"
                bold: True
                color: 1, 1, 1, 1

                # DarkTab’ın kendi arkaplanını devre dışı bırak
                background_normal: ""
                background_down: ""
                background_color: 0, 0, 0, 0

                on_release: root.open_make_profile_confirm()

                # ✅ Profile Start butonuyla AYNI MANTIK
                canvas.before:
                    Color:
                        rgba: (0.10, 0.50, 0.15, 1) if int(root.m501_state) == 1 else (0.18, 0.20, 0.25, 1)
                    RoundedRectangle:
                        pos: self.pos
                        size: self.size
                        radius: [dp(26), dp(26), dp(26), dp(26)]

            DarkTab:
                text: "Profile"
                tab_key: "profile"
                font_size: "25sp"
                bold: True
                color: 1, 1, 1, 1
                on_release: root.open_profile_tab()
                #on_release: root.manager.current = "profile"

        # ---------------- MAIN ROW ----------------
        BoxLayout:
            spacing: dp(12)
            size_hint_y: 1

            # =================================================
            # LEFT PANEL
            # =================================================
            Card:
                size_hint_x: None
                size_hint_y: 1
                width: dp(240)

                AnchorLayout:
                    anchor_x: "center"
                    anchor_y: "top"

                    BoxLayout:
                        orientation: "vertical"
                        spacing: dp(12)
                        size_hint_y: None
                        height: self.minimum_height

                        # ---- SET VALUE ----
                        Label:
                            text: "Set Value"
                            font_size: "25sp"
                            bold: False
                            color: 1, 1, 1, 1
                            size_hint_y: None
                            height: dp(22)

                        ClickLabel:
                            text: root.set_text
                            font_size: "36sp"
                            bold: False
                            color: 0.95, 0.80, 0.35, 1
                            size_hint_y: None
                            height: dp(34)
                            on_release: root.open_set_value_keypad()

                        Widget:
                            size_hint_y: None
                            height: dp(18)

                        # ---- BEAN TEMP ----
                        Label:
                            text: "Bean Temp"
                            font_size: "25sp"
                            bold: False
                            color: 1, 1, 1, 1
                            size_hint_y: None
                            height: dp(22)

                        Label:
                            text: root.bean_text
                            font_size: "36sp"
                            bold: False
                            color: 0.95, 0.72, 0.35, 1
                            size_hint_y: None
                            height: dp(34)

                        Widget:
                            size_hint_y: None
                            height: dp(18)

                        # ---- ENV TEMP ----
                        Label:
                            text: "Exhaust TEMP"
                            font_size: "25sp"
                            bold: False
                            color: 1, 1, 1, 1
                            size_hint_y: None
                            height: dp(22)

                        Label:
                            text: root.env_text
                            font_size: "36sp"
                            bold: False
                            color: 0.95, 0.64, 0.35, 1
                            size_hint_y: None
                            height: dp(34)

                        Widget:
                            size_hint_y: None
                            height: dp(24)

                        # ---- EXHAUST SPEED (GAUGE) ----
                        AnchorLayout:
                            size_hint_y: None
                            height: dp(100)
                            anchor_x: "center"
                            anchor_y: "center"

                            AirflowGauge:
                                size_hint: None, None
                                size: dp(160), dp(160)
                                value: root.exhaust_ratio
                                gauge_color: 0.25, 0.45, 0.75, 1

                            BoxLayout:
                                orientation: "vertical"
                                size_hint: None, None
                                size: dp(160), dp(50)
                                spacing: dp(2)
                                pos_hint: {"center_x": 0.5, "center_y": 0.45}

                                ClickLabel:
                                    text: root.speed_text
                                    font_size: "34sp"
                                    bold: False
                                    color: 0.95, 0.85, 0.35, 1
                                    halign: "center"
                                    valign: "middle"
                                    text_size: self.size
                                    on_release: root.open_exhaust_speed_keypad()

                                Label:
                                    text: "Exhaust"
                                    font_size: "22sp"
                                    color: 1, 1, 1, 1
                                    halign: "center"
                                    valign: "middle"
                                    text_size: self.size

                        Widget:
                            size_hint_y: None
                            height: dp(1)

                        # ---- BURNER GAUGE ----
                        AnchorLayout:
                            size_hint_y: None
                            height: dp(100)
                            anchor_x: "center"
                            anchor_y: "center"

                            AirflowGauge:
                                size_hint: None, None
                                size: dp(160), dp(160)
                                value: root.burner_ratio
                                gauge_color: 0.90, 0.55, 0.25, 1

                            BoxLayout:
                                orientation: "vertical"
                                size_hint: None, None
                                size: dp(160), dp(50)
                                spacing: dp(2)
                                pos_hint: {"center_x": 0.5, "center_y": 0.45}

                                ClickLabel:
                                    text: root.burner_text
                                    font_size: "34sp"
                                    bold: False
                                    color: 0.95, 0.85, 0.35, 1
                                    halign: "center"
                                    valign: "middle"
                                    text_size: self.size
                                    on_release: root.open_burner_keypad()

                                Label:
                                    text: "Burner"
                                    font_size: "26sp"
                                    color: 1, 1, 1, 1
                                    halign: "center"
                                    valign: "middle"
                                    text_size: self.size

                        Widget:
                            size_hint_y: None
                            height: dp(1)

                        # ---- AIRFLOW GAUGE ----
                        AnchorLayout:
                            size_hint_y: None
                            height: dp(100)
                            anchor_x: "center"
                            anchor_y: "center"

                            AirflowGauge:
                                size_hint: None, None
                                size: dp(160), dp(160)
                                value: root.airflow_ratio
                                gauge_color: 0.30, 0.65, 0.45, 1

                            BoxLayout:
                                orientation: "vertical"
                                size_hint: None, None
                                size: dp(160), dp(50)
                                spacing: dp(2)
                                pos_hint: {"center_x": 0.5, "center_y": 0.45}

                                Label:
                                    text: root.airflow_text
                                    font_size: "34sp"
                                    bold: False
                                    color: 0.95, 0.70, 0.35, 1
                                    halign: "center"
                                    valign: "middle"
                                    text_size: self.size

                                Label:
                                    text: "Airflow."
                                    font_size: "20sp"
                                    color: 1, 1, 1, 1
                                    halign: "center"
                                    valign: "middle"
                                    text_size: self.size

            # =================================================
            # CENTER PANEL (PLOT)
            # =================================================
            Card:
                size_hint_y: 1

                FloatLayout:
                    id: plot_layer

                    RoastPlot:
                        id: plot
                        size_hint: None, None
                        pos: self.parent.pos
                        size: self.parent.size

                    # --- LONG PRESS overlay (2s) ---
                    PlotHoldArea:
                        id: plot_hold
                        size_hint: None, None
                        pos: plot.pos
                        size: plot.size

                        on_press: root._plot_hold_start()
                        on_release: root._plot_hold_cancel()

                    # =====================================================
                    # PROFILE OVERLAY (TOP-LEFT, GRID, LABEL ONLY, TRANSPARENT)
                    # =====================================================
                    GridLayout:
                        id: profile_overlay
                        cols: 4
                        spacing: dp(14), dp(10)
                        row_force_default: True
                        row_default_height: dp(24)

                        size_hint: None, None
                        width: dp(660)
                        height: self.minimum_height

                        # SOL ÜSTTE ama biraz SAĞA KAYDIR
                        x: self.parent.x + dp(90)
                        y: self.parent.y + self.parent.height - self.height - dp(14)

                        canvas.before:
                            Color:
                                rgba: 0, 0, 0, 0
                            Rectangle:
                                pos: self.pos
                                size: self.size

                        # ---- HEADER ROW ----
                        Label:
                            text: "PROFILE"
                            width: dp(260)   # 👈 İLK KOLON GENİŞ
                            font_size: "18sp"
                            bold: True
                            color: 1, 1, 1, 1
                            halign: "left"
                            valign: "middle"
                            text_size: self.size

                        Label:
                            text: "Temperature"
                            font_size: "18sp"
                            bold: True
                            color: 0.78, 0.80, 0.86, 1
                            halign: "center"
                            valign: "middle"
                            text_size: self.size

                        Label:
                            text: "Exhaust"
                            font_size: "18sp"
                            bold: True
                            color: 0.78, 0.80, 0.86, 1
                            halign: "center"
                            valign: "middle"
                            text_size: self.size

                        Label:
                            text: "Flame"
                            font_size: "18sp"
                            bold: True
                            color: 0.78, 0.80, 0.86, 1
                            halign: "center"
                            valign: "middle"
                            text_size: self.size

                        # ---- ROW 1 ----
                        Label:
                            text: "Drop Down Temp"
                            font_size: "17sp"
                            bold: True
                            color: 0.70, 0.72, 0.78, 1
                            halign: "left"
                            valign: "middle"
                            text_size: self.size

                        Label:
                            id: ov_dd_val
                            text: "-- °C"
                            font_size: "17sp"
                            bold: True
                            color: 0.90, 0.90, 0.90, 1
                            halign: "center"
                            valign: "middle"
                            text_size: self.size

                        Label:
                            id: ov_dd_exh
                            text: "-- %"
                            font_size: "17sp"
                            bold: True
                            color: 0.90, 0.90, 0.90, 1
                            halign: "center"
                            valign: "middle"
                            text_size: self.size

                        Label:
                            id: ov_dd_flm
                            text: "-- %"
                            font_size: "17sp"
                            bold: True
                            color: 0.90, 0.90, 0.90, 1
                            halign: "center"
                            valign: "middle"
                            text_size: self.size

                        # ---- ROW 2 ----
                        Label:
                            text: "Hopper Open Time"
                            font_size: "17sp"
                            bold: True
                            color: 0.70, 0.72, 0.78, 1
                            halign: "left"
                            valign: "middle"
                            text_size: self.size

                        Label:
                            id: ov_hop_val
                            text: "-- sec."
                            font_size: "17sp"
                            bold: True
                            color: 0.90, 0.90, 0.90, 1
                            halign: "center"
                            valign: "middle"
                            text_size: self.size

                        Label:
                            id: ov_hop_exh
                            text: "-- %"
                            font_size: "17sp"
                            bold: True
                            color: 0.90, 0.90, 0.90, 1
                            halign: "center"
                            valign: "middle"
                            text_size: self.size

                        Label:
                            id: ov_hop_flm
                            text: "-- %"
                            font_size: "17sp"
                            bold: True
                            color: 0.90, 0.90, 0.90, 1
                            halign: "center"
                            valign: "middle"
                            text_size: self.size



                        # ---- NEW ROW (Chaffing) ----
                        Label:
                            text: "Chaffing (sec)"
                            font_size: "17sp"
                            bold: True
                            color: 0.70, 0.72, 0.78, 1
                            halign: "left"
                            valign: "middle"
                            text_size: self.size

                        Label:
                            id: ov_ch_val
                            text: "-- sec"
                            font_size: "17sp"
                            bold: True
                            color: 0.90, 0.90, 0.90, 1
                            halign: "center"
                            valign: "middle"
                            text_size: self.size

                        Label:
                            id: ov_ch_exh
                            text: "-- %"
                            font_size: "17sp"
                            bold: True
                            color: 0.90, 0.90, 0.90, 1
                            halign: "center"
                            valign: "middle"
                            text_size: self.size

                        Label:
                            id: ov_ch_flm
                            text: "-- %"
                            font_size: "17sp"
                            bold: True
                            color: 0.90, 0.90, 0.90, 1
                            halign: "center"
                            valign: "middle"
                            text_size: self.size

                        # ---- NEW ROW (Chaffing Time) ----
                        Label:
                            text: "Chaffing Time (sec)"
                            font_size: "17sp"
                            bold: True
                            color: 0.70, 0.72, 0.78, 1
                            halign: "left"
                            valign: "middle"
                            text_size: self.size

                        Label:
                            id: ov_cht_val
                            text: "-- sec"
                            font_size: "17sp"
                            bold: True
                            color: 0.90, 0.90, 0.90, 1
                            halign: "center"
                            valign: "middle"
                            text_size: self.size

                        Label:
                            id: ov_cht_exh
                            text: "-- %"
                            font_size: "17sp"
                            bold: True
                            color: 0.90, 0.90, 0.90, 1
                            halign: "center"
                            valign: "middle"
                            text_size: self.size

                        Label:
                            id: ov_cht_flm
                            text: "-- %"
                            font_size: "17sp"
                            bold: True
                            color: 0.90, 0.90, 0.90, 1
                            halign: "center"
                            valign: "middle"
                            text_size: self.size




                        # ---- ROW 3 ----
                        Label:
                            text: "First Crack Temp"
                            font_size: "17sp"
                            bold: True
                            color: 0.70, 0.72, 0.78, 1
                            halign: "left"
                            valign: "middle"
                            text_size: self.size

                        Label:
                            id: ov_fc_val
                            text: "-- °C"
                            font_size: "17sp"
                            bold: True
                            color: 0.90, 0.90, 0.90, 1
                            halign: "center"
                            valign: "middle"
                            text_size: self.size

                        Label:
                            id: ov_fc_exh
                            text: "-- %"
                            font_size: "17sp"
                            bold: True
                            color: 0.90, 0.90, 0.90, 1
                            halign: "center"
                            valign: "middle"
                            text_size: self.size

                        Label:
                            id: ov_fc_flm
                            text: "-- %"
                            font_size: "17sp"
                            bold: True
                            color: 0.90, 0.90, 0.90, 1
                            halign: "center"
                            valign: "middle"
                            text_size: self.size

                        # ---- ROW 4 (Second Crack  /  DEV -> Development Time) ----
                        Label:
                            text: "Second Crack Temp" if root.profile_mode != "dev" else "Development Time"
                            font_size: "17sp"
                            bold: True
                            color: (0.70, 0.72, 0.78, 1) if root.profile_mode != "dev" else (0.70, 0.72, 0.78, 1)
                            halign: "left"
                            valign: "middle"
                            text_size: self.size
                            size_hint_y: None
                            height: dp(24)
                            opacity: 1
                            disabled: False

                        Label:
                            id: ov_sc_val
                            text: ("-- °C" if root.profile_mode != "dev" else (root.dev_time_min + ":" + root.dev_time_sec))
                            font_size: "17sp"
                            bold: True
                            color: 0.90, 0.90, 0.90, 1
                            halign: "center"
                            valign: "middle"
                            text_size: self.size
                            size_hint_y: None
                            height: dp(24)
                            opacity: 1
                            disabled: False

                        Label:
                            id: ov_sc_exh
                            text: ("-- %" if root.profile_mode != "dev" else "--")
                            font_size: "17sp"
                            bold: True
                            color: 0.90, 0.90, 0.90, 1
                            halign: "center"
                            valign: "middle"
                            text_size: self.size
                            size_hint_y: None
                            height: dp(24)
                            opacity: 1
                            disabled: False

                        Label:
                            id: ov_sc_flm
                            text: ("-- %" if root.profile_mode != "dev" else "--")
                            font_size: "17sp"
                            bold: True
                            color: 0.90, 0.90, 0.90, 1
                            halign: "center"
                            valign: "middle"
                            text_size: self.size
                            size_hint_y: None
                            height: dp(24)
                            opacity: 1
                            disabled: False

                        # ---- ROW 5 (Drop Out) ----
                        Label:
                            text: "DROP OUT TEMP"
                            font_size: "17sp"
                            bold: True
                            color: 0.78, 0.80, 0.86, 1
                            halign: "left"
                            valign: "middle"
                            text_size: self.size
                            size_hint_y: None
                            height: dp(24) if root.profile_mode != "dev" else 0
                            opacity: 1 if root.profile_mode != "dev" else 0
                            disabled: True if root.profile_mode == "dev" else False

                        Label:
                            id: ov_out_val
                            text: "-- °C"
                            font_size: "17sp"
                            bold: True
                            color: 0.90, 0.90, 0.90, 1
                            halign: "center"
                            valign: "middle"
                            text_size: self.size
                            size_hint_y: None
                            height: dp(24) if root.profile_mode != "dev" else 0
                            opacity: 1 if root.profile_mode != "dev" else 0
                            disabled: True if root.profile_mode == "dev" else False

                        Label:
                            id: ov_out_exh
                            text: "-- %"
                            font_size: "17sp"
                            bold: True
                            color: 0.90, 0.90, 0.90, 1
                            halign: "center"
                            valign: "middle"
                            text_size: self.size
                            size_hint_y: None
                            height: dp(24) if root.profile_mode != "dev" else 0
                            opacity: 1 if root.profile_mode != "dev" else 0
                            disabled: True if root.profile_mode == "dev" else False

                        Label:
                            id: ov_out_flm
                            text: "-- %"
                            font_size: "17sp"
                            bold: True
                            color: 0.90, 0.90, 0.90, 1
                            halign: "center"
                            valign: "middle"
                            text_size: self.size
                            size_hint_y: None
                            height: dp(24) if root.profile_mode != "dev" else 0
                            opacity: 1 if root.profile_mode != "dev" else 0
                            disabled: True if root.profile_mode == "dev" else False



                    # ===== Message banner (legend üstü, sol alt) =====
                    BoxLayout:
                        id: msg_banner
                        size_hint: None, None

                        height: dp(46) if root.banner_text else 0
                        width: dp(360) if root.banner_text else 0
                        opacity: 1 if root.banner_text else 0
                        disabled: True if not root.banner_text else False

                        x: self.parent.x + dp(60)
                        y: self.parent.y + dp(58)

                        padding: dp(12), dp(8)
                        spacing: dp(8)

                        Label:
                            text: root.banner_text
                            font_size: "18sp"
                            color: 0.95, 0.85, 0.35, 1
                            halign: "left"
                            valign: "middle"
                            text_size: self.size

            # =================================================
            # RIGHT PANEL
            # =================================================
            Card:
                size_hint_x: None
                size_hint_y: 1
                width: dp(240)

                AnchorLayout:
                    anchor_x: "center"
                    anchor_y: "top"

                    BoxLayout:
                        orientation: "vertical"
                        spacing: dp(12)
                        size_hint_y: None
                        height: self.minimum_height

                        # ---- ROASTING TIME ----
                        Label:
                            text: "Roasting Time"
                            font_size: "25sp"
                            bold: False
                            color: 1, 1, 1, 1
                            size_hint_y: None
                            height: dp(22)

                        Label:
                            text: root.roasttime_text
                            font_size: "36sp"
                            bold: False
                            color: 0.95, 0.85, 0.35, 1
                            size_hint_y: None
                            height: dp(34)

                        Widget:
                            size_hint_y: None
                            height: dp(20)

                        # ---- DRYING TIME ----
                        Label:
                            text: "Drying Time"
                            font_size: "25sp"
                            bold: False
                            color: 1, 1, 1, 1
                            size_hint_y: None
                            height: dp(22)

                        Label:
                            text: root.drytime_text
                            font_size: "36sp"
                            bold: False
                            color: 0.95, 0.72, 0.35, 1
                            size_hint_y: None
                            height: dp(34)

                        Widget:
                            size_hint_y: None
                            height: dp(20)

                        # ---- MILLARD TIME ----
                        Label:
                            text: "Milliard Time"
                            font_size: "25sp"
                            bold: False
                            color: 1, 1, 1, 1
                            size_hint_y: None
                            height: dp(22)

                        Label:
                            text: root.miltime_text
                            font_size: "36sp"
                            bold: False
                            color: 0.95, 0.64, 0.35, 1
                            size_hint_y: None
                            height: dp(34)

                        Widget:
                            size_hint_y: None
                            height: dp(20)

                        # ---- DEVELOPMENT TIME ----
                        Label:
                            text: "Development Time"
                            font_size: "25sp"
                            bold: False
                            color: 1, 1, 1, 1
                            size_hint_y: None
                            height: dp(22)

                        Label:
                            text: root.devtime_text
                            font_size: "36sp"
                            bold: False
                            color: 0.95, 0.56, 0.35, 1
                            size_hint_y: None
                            height: dp(34)

                        Widget:
                            size_hint_y: None
                            height: dp(10)

                        # ---- ROR ----
                        Label:
                            text: "Rate Of Rise"
                            font_size: "25sp"
                            bold: True
                            color: 1, 1, 1, 1
                            size_hint_y: None
                            height: dp(22)

                        BoxLayout:
                            orientation: "vertical"
                            size_hint_y: None
                            height: dp(100)
                            spacing: dp(20)

                            Label:
                                text: root.ror_text
                                font_size: "34sp"
                                bold: False
                                color: 0.95, 0.48, 0.35, 1
                                halign: "center"
                                valign: "middle"
                                text_size: self.size

                            Label:
                                text: root.ror_max_text
                                font_size: "34sp"
                                bold: False
                                color: 0.95, 0.40, 0.35, 1
                                halign: "center"
                                valign: "middle"
                                text_size: self.size

                            Label:
                                text: root.C_sec_text
                                font_size: "34sp"
                                bold: False
                                color: 0.55, 0.85, 0.65, 1
                                halign: "left"
                                valign: "middle"
                                text_size: self.size

                                opacity: 0
                                disabled: True
                                size_hint_y: None
                                height: 0

                        Widget:
                            size_hint_y: None
                            height: dp(0)

                        # ---- EXTRA BUTTON (below ROR) ----
                        Button:
                            text: "Profile Stop" if int(root.m500_state) == 1 else "Profile Start"
                            font_size: "24sp"
                            bold: True
                            size_hint_y: None
                            height: dp(70)
                            background_normal: ""
                            background_down: ""
                            background_color: 0, 0, 0, 0
                            on_release: root.open_profile_fullscreen_popup()

                            canvas.before:
                                Color:
                                    rgba: (0.10, 0.70, 0.20, 1) if int(root.m500_state) == 1 else (0.16, 0.17, 0.20, 1)
                                RoundedRectangle:
                                    pos: self.pos
                                    size: self.size
                                    radius: [dp(18), dp(18), dp(18), dp(18)]